version: "2.18.1"
services:
  db:
    image: postgres:14.11
    env_file:
      - .env-non-dev
    command: -p 5433
    expose:
      - 5433
    ports:
      - 5433:5433
    volumes:
      - database:/var/lib.postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: botco_fastapi
    ports:
      - 8001:8001
    depends_on:
      - db
    command: ["/botco_fastapi/app.sh"]
    volumes:
      - .:/usr/src/app

volumes:
  database: null