[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | __pycache__
    | .idea
    | venv
    | website
  )/
)
'''

[tool.pytest.ini_options]
pythonpath = [
    ".",
    "src",
]
asyncio_mode="auto"
filterwarnings="ignore::DeprecationWarning"