"""remove log model

Revision ID: 7581f920a1fd
Revises: 66db24f65a3f
Create Date: 2024-05-25 13:06:16.568455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7581f920a1fd'
down_revision: Union[str, None] = '66db24f65a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fastapi_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['fastapi_bot.id'], name='fastapi_log_bot_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fastapi_log_pkey')
    )
    # ### end Alembic commands ###
